### ISSUE TITLE
[Question] Is it going to be released in Maven Central Repo?

### ISSUE THREAD

**Issue by lordofthejars** [poynt/postman-runner#1]
[Question] Is it going to be released in Maven Central Repo?

**Comment by vchau** [comment]
Hi @lordofthejars , I have not thought about submitting it to Maven central yet.  If there's more request for it, i might go through the process.  Hopefully, the Maven central repo submission process is less painful than the last time I went through it a number of years ago.

**Comment by lordofthejars** [comment]
I think it is pretty much the same, also are you accepting PR? We would like to do deep changes on the application like replacing some libraries like spring or jackson to lighter ones, set as minimum version Java 8 with Nashorn instead of Rhino (we need to explore) or introduce a logger. I understand that these are massive changes, so we totally understand that you might want to maintain the current code base.

**Comment by vchau** [comment]
Yes, we are always open to PR if it helps improve the code quality and performance.  All the things you've mentioned are something I've been wanting to do for awhile; just haven't had the time. Especially the spring dependency.

**Comment by lordofthejars** [comment]
Great we are going to provide a PR with some changes for sure. BTW where is this file? `PoyntRegression.postman_collection` Just to be able to run the test.

**Comment by vchau** [comment]
That file is an internal test script of ours (yup, we use this tool internally.)  You can create a simple collection by creating one in the POSTMAN client and exporting from it (as a Collection V1 format).

**Comment by lordofthejars** [comment]
Is V1 the most used or V2 is the most one?

**Comment by vchau** [comment]
I am unsure as to the adoption rate in the wild but we at Poynt have not found a need to migrate to V2 since from a functional perspective, there isn't any difference to the tests.

**Comment by ejferreira** [comment]
+1 for this tool to be published in Maven Central.

**Comment by lordofthejars** [comment]
Currently I reimplemented in arquillian ape 2.x the same feature
https://github.com/arquillian/arquillian-extension-persistence/tree/2.0.0/arquillian-ape-rest/postman-ftest

**Comment by YounesRahimi** [comment]
+1 for this tool to be published in Maven Central. This tool is very interesting.

**Comment by vchau** [comment]
Hi Guys, I've just published it to maven central.  The first version published is 1.0.9 https://repo.maven.apache.org/maven2/co/poynt/postman/runner/postman-runner/1.0.9/
