### ISSUE TITLE
Unit Test are Not working

### ISSUE THREAD

**Issue by b4dw017** [poynt/postman-runner#11]
I clone the project and ran the test Load a file which is not working

**Comment by vchau** [comment]
Hello @b4dw017,
Can you give bit more details on the steps you did to reproduce the issue?  If you were using the shell script provided in the /bin folder, it had an older version of the jar that does not work with the latest Postman collection format.  I just updated it to latest jar and should be compatible with Postman collection 2.1 format.

**Comment by vchau** [comment]
I just realized what you are referring to.  I've fixed the issue.

**Comment by jharri34** [comment]
Hey sorry, for the late response what I'm talking about is that if I clone the project and run the included test, it fails due to not being able to find the file
