### ISSUE TITLE
incorrect variable substitution

### ISSUE THREAD

**Issue by sandeepkalluri** [poynt/postman-runner#16]
variable substitution logic is kicked in for {{ ABC }} incorrectly, which has to happen only for this case {{ABC}}, actual problem i'm using jinja2 template in my request body, the body gets INVALID value substibuted in the parameter. From the code i could see there is issue with pattern used for the variable substitution.

Matcher m = Pattern.compile("\\{\\{[^\\}]+\\}\\}").matcher(orig);
Instead we could use
Matcher m = Pattern.compile("\\{\\{[^\\}\s]+\\}\\}").matcher(orig);
which also does not match for the spaces in the string.

**Comment by vchau** [comment]
Ic, you are suggesting to add the `\s` to also match any white space? I'll try it out and get back to you soon.

**Comment by vchau** [comment]
This should fix it https://github.com/poynt/postman-runner/commit/39b625905bc0c4f1319f177a26273514607ff2d9
