### ISSUE TITLE
Please provide information for run this code

### ISSUE THREAD

**Issue by rishikeshs** [poynt/postman-runner#3]
Hi all, 
I am new to REST API and Postman. I want to invoke postman collection V1 from Java code. But I am ambiguous about following problems:

<groupId>co.poynt.postman.runner</groupId>
<artifactId>postman-runner</artifactId>
<version>x.x.x</version>

in x.x.x which version I need to write here?
Second I only want to run my Postman collection file, I dont have any environment, folder file. In case of this What parameters should I passed for -e, -f and -haltanerror? Because if I am right all these parameters are mandatory to run Postman.

**Comment by b4dw017** [comment]
1) 2.0.0.0

**Comment by vchau** [comment]
Hi @rishikeshs 
Apologize for such this late reply.  The postman-runner 2.0.2 is latest version which supports collection v2.1.  You can simply provide an empty environment file if your collection does not have any environment info.  Unfortunately, the code still expects an environment file.
