### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by trufflepig** [poynt/postman-runner#4]
Using version 1.0.9 to run postman tests from within a maven project and had problems running existing tests due to the following:
1. Postman-runner has a testng dependency which was being picked up by the maven failsafe plugin which then stopped our junit tests running. It would be nice if I didn't have to wrestle with pom.xml settings and could use postman-runner out of the box - perhaps there should be two versions: one based on testng, the other based on junit.
2. Postman-runner also has a jackson dependency on an old version which also clashed with our tests that use some features from a newer version (2.3.2 versus 2.8.10). A more up to date build would be nice.

**Comment by vchau** [comment]
I've moved the testng dependency into the `test` scope, which should not conflict with your junit dependency.

Updated to Jackson 2.9.3

**Comment by sheldon-sminq** [comment]
So can this be used along with Junit? we are using Vertx Junit and i am trying to integrate this as part of the test flow with no success yet.
